version: '3.3'

services:
  mysql:
    image: mysql:5
    environment:
      - MYSQL_DATABASE=my_store
      - MYSQL_ROOT_USERNAME=root
      - MYSQL_ROOT_PASSWORD=admin123
      - MYSQL_PORT=3306
    networks:
      - rentail-application

  mongodb:
    image: mongo
    restart: always
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_USERNAME: db_application
      MONGO_INITDB_PASSWORD: superSecret
      MONGO_INITDB_DATABASE: bd-rental
          
  reserva:
    image: reserva:013
    environment:
      - MYSQL_BD=my_store
      - MYSQL_USUARIO=root
      - MYSQL_CONTRASEÑA=admin123
      - MYSQL_PORT=8080
      - MYSQL_HOST=mysql
      - MONGO_USUARIO=root
      - MONGO_CONTRASEÑA=example
      - MONGO_BD=bd-rental
    ports:
      - 8080:8080
    networks:
      - rentail-application

networks:
  rentail-application:
    driver: bridge