name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
          node-version: 14.x
    - name: Install Dependencies
      run: npm ci
    - name: Build
      run: npm run build
    - name: Docker Login
      uses: docker/login-action@v1.10.0
      with:
        username: ${{ secrets.DOCKER_USERNAME}}
        password: ${{ secrets.DOCKER_PASSWORD}}
        logout: true
    - name: Docker Push
      run: |
        export VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
        docker build -t nicolasdockerbdb/observer-rental-service:$VERSION .
        docker tag nicolasdockerbdb/observer-rental-service:$VERSION nicolasdockerbdb/observer-rental-service:latest
        docker push nicolasdockerbdb/observer-rental-service:$VERSION
        docker push nicolasdockerbdb/observer-rental-service:latest
